[package]
name = "macros"
version = "0.0.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.91", features = ["full", "extra-traits"] }
quote = "1.0.18"
proc-macro2 = "1.0.32"
